name: Build-Linux

on:
  push:
    branches: [ main, Main, experimental, Experimental ]
  workflow_dispatch:

jobs:
  call-linux-64bit:
    uses: .github/workflows/master.yml@experimental
    with:
      os: ubuntu-latest
      setupScript: |
        sudo apt install libvlc-dev libvlccore-dev
        haxelib setup ~/haxelib
        haxelib install hxcpp > /dev/null --quiet
        chmod +x ./setup/unix.sh
        sh ./setup/unix.sh
      buildArgs: linux -D officialBuild -D message.reporting=pretty -D HXCPP_GC_BIG_BLOCKS -D hscriptPos -D HXCPP_CATCH_SEGV
      artifactName: UPF-linuxBuild-64bit
      artifactPath: export/release/linux/64bit/bin

  call-linux-32bit:
    uses: .github/workflows/master.yml@experimental
    with:
      os: ubuntu-latest
      setupScript: |
        sudo apt install libvlc-dev libvlccore-dev
        haxelib setup ~/haxelib
        haxelib install hxcpp > /dev/null --quiet
        chmod +x ./setup/unix.sh
        sh ./setup/unix.sh
      buildArgs: linux -D officialBuild -D message.reporting=pretty -D HXCPP_GC_BIG_BLOCKS -D hscriptPos -D HXCPP_CATCH_SEGV -D HXCPP_32BIT
      artifactName: UPF-linuxBuild-32bit
      artifactPath: export/release/linux/32bit/bin
