name: Build

on:
  push:
    branches: [ main, Main, experimental, Experimental ]
  pull_request:
    branches: [ main, Main, experimental, Experimental ]
  workflow_dispatch:

jobs:
  find-master:
    uses: ./.github/workflows/Master.yml
