name: Build All Platforms

on:
  workflow_dispatch:

env:
  HAXE_VERSION: 4.3.6
  PROJECT_NAME: UPF

jobs:
  build-windows:
    uses: ./windows.yml
    with:
      name: "Windows"
      os: "windows-latest"
      setupScript: '.\"setup/windows.bat"'
      buildArgs: 'Project.xml windows -D officialBuild'
      artifactName: "UPF-windows"
      artifactPath: "export/release/windows/bin"

  build-linux:
    uses: ./linux.yml
    with:
      name: "Linux"
      os: "ubuntu-latest"
      setupScript: 'chmod +x ./setup/unix.sh && sh ./setup/unix.sh'
      buildArgs: 'Project.xml linux -D officialBuild'
      artifactName: "UPF-linux"
      artifactPath: "export/release/linux/bin"

  build-mac:
    uses: ./mac.yml
    with:
      name: "macOS"
      os: "macos-latest"
      setupScript: 'chmod +x ./setup/unix.sh && sh ./setup/unix.sh'
      buildArgs: 'Project.xml mac -D officialBuild'
      artifactName: "UPF-mac"
      artifactPath: "export/release/macos/bin"
